CREATE TABLE IF NOT EXISTS PRODUCTO(
	CODIGO VARCHAR(4) PRIMARY KEY,
    NOMBRE VARCHAR(20),
    UNIDADES INT(2)
);

CREATE TABLE IF NOT EXISTS PERSONA(
	CODIGO VARCHAR(3) PRIMARY KEY,
    NOMBRE VARCHAR(20),
    EDAD INT(2)
);