CREATE DATABASE EMPLEADOS;
USE EMPLEADOS;

CREATE TABLE DEPARTAMENTOS(
	CODIGO CHAR(3) PRIMARY KEY,
    NOMBRE VARCHAR(20),
    PRESUPUESTO FLOAT);

CREATE TABLE EMPLEADOS(
	DNI CHAR(9) PRIMARY KEY,
    NOMBRE VARCHAR(20),
    APELLIDOS VARCHAR(20),
    DEPARTAMENTO CHAR(3),
    CONSTRAINT emp_dep_fk FOREIGN KEY (DEPARTAMENTO) REFERENCES DEPARTAMENTOS(CODIGO) ON UPDATE CASCADE ON DELETE SET NULL);
    
INSERT INTO DEPARTAMENTOS VALUES(11, 'CALIDAD', 40000);
INSERT INTO EMPLEADOS VALUES(89267109, 'ESTHER', 'VASQUEZ', 11);

UPDATE DEPARTAMENTOS SET PRESUPUESTO = PRESUPUESTO * 0.9;

INSERT INTO DEPARTAMENTOS VALUES(77, 'INVESTIGACION', 10000);
INSERT INTO DEPARTAMENTOS VALUES(14, 'INFORMATICA', 90000);
INSERT INTO EMPLEADOS VALUES(123456789, 'JULIO', 'RODRIGUEZ', 77);
INSERT INTO EMPLEADOS VALUES(123456782, 'CARLA', 'RODRIGUEZ', 14);
SELECT * FROM EMPLEADOS;
SELECT * FROM DEPARTAMENTOS;
UPDATE EMPLEADOS SET DEPARTAMENTO = (SELECT CODIGO FROM DEPARTAMENTOS WHERE NOMBRE = 'INFORMATICA') WHERE DEPARTAMENTO = (SELECT CODIGO FROM DEPARTAMENTOS WHERE NOMBRE = 'INVESTIGACION');

DELETE FROM EMPLEADOS WHERE DEPARTAMENTO = (SELECT CODIGO FROM DEPARTAMENTOS WHERE NOMBRE = 'INFORMATICA');

DELETE FROM EMPLEADOS WHERE DEPARTAMENTO IN(SELECT CODIGO FROM DEPARTAMENTOS WHERE PRESUPUESTO > 60000);

DELETE FROM EMPLEADOS;