CREATE DATABASE IF NOT EXISTS PROVEEDORES;
USE PROVEEDORES;

CREATE TABLE PIEZAS(
	CODIGO CHAR(4) PRIMARY KEY,
    NOMBRE VARCHAR(40));

CREATE TABLE PROVEEDOR(
	ID CHAR(3) PRIMARY KEY,
    NOMBRE VARCHAR(40));

CREATE TABLE SUMINISTRAN(
	COD_PIEZA CHAR(4),
    ID_PROV CHAR(3),
    PRECIO FLOAT,
    CONSTRAINT SUM_PK PRIMARY KEY (COD_PIEZA, ID_PROV),
    CONSTRAINT SUM_ID_FK FOREIGN KEY (ID_PROV) REFERENCES PROVEEDOR(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT SUM_COD_FK FOREIGN KEY (COD_PIEZA) REFERENCES PIEZAS(CODIGO) ON UPDATE CASCADE ON DELETE CASCADE);
    

INSERT INTO PROVEEDOR VALUES('TNB', 'SKELLINGTON');
INSERT INTO PIEZAS VALUES('0001', 'TUERCAS');
INSERT INTO SUMINISTRAN VALUES('0001', 'TNB', 7);

UPDATE SUMINISTRAN SET PRECIO = PRECIO + 1;

INSERT INTO PROVEEDOR VALUES('RBT','SUSAN CALVIN');

